name: WikiEnconet
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip=26.2.1
  - pip:
      - pandas==3.0.3
      - openpyxl==3.1.5
      - typer==0.17.4
      - rich==14.2.0
      - PyYAML==6.0.3
      - pytest==9.1.1
      - pytest-cov==7.1.0
      - playwright==1.62.0
