"""Render and validate the CC_Loto Slice 2 coordination core.

The output is written only after validation in a disposable target root. The
committed rendered tree is the byte authority for a later reviewed target write.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path


WIKI = Path(__file__).resolve().parents[3]
TEMPLATES = WIKI / "doc/support-transfer/templates/coordination"
STAGED = WIKI / "doc/support-transfer/staged"
OUT = WIKI / "doc/support-transfer/rendered/loto-slice2"
LOTO = Path("C:/xPY/xPrj/CC_Loto")

sys.path.insert(0, str(STAGED))
from _shared import scan_sensitive  # noqa: E402


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--timestamp", help="fixed UTC BOARD timestamp (YYYY-MM-DDTHH:MM:SSZ)")
args = parser.parse_args()
if args.timestamp:
    datetime.strptime(args.timestamp, "%Y-%m-%dT%H:%M:%SZ")
NOW = args.timestamp or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise AssertionError(f"{label}: expected one replacement site, found {count}")
    return text.replace(old, new)


ownership = (
    "The human project owner approves gates, authority changes, destructive recovery, "
    "hosted-governance changes, and releases. Codex owns `AGENTS.md`, `.agents/`, and "
    "`CX_` records. Claude Code owns `CLAUDE.md`, `.claude/`, and `CC_` records. "
    "Coordination records without an agent prefix, schemas, templates, validators, "
    "claims, the generated board, support logs, and handoffs are shared-neutral by "
    "contract. An agent may inspect but must not edit or archive the other agent's "
    "owned infrastructure or prefixed records."
)

team_protocol = (TEMPLATES / "TEAM_PROTOCOL.template.md").read_text(encoding="utf-8")
team_protocol = team_protocol.replace("{{PROJECT_NAME}}", "CC_Loto")
team_protocol = team_protocol.replace("{{AGENT_OWNERSHIP_SUMMARY}}", ownership)
team_protocol = team_protocol.replace("{{SUPPORT_PROFILE_PATH}}", "support/PROFILE.md")

validator = (STAGED / "coordination_validator.py").read_text(encoding="utf-8")
validator = re.sub(
    r'\A""".*?"""',
    '"""CC_Loto target-local coordination validator and BOARD renderer.\n\n'
    'Run from the repository root as ``python tools/support/agent_coord.py .``.\n'
    'BOARD.md is generated state, never authority. Before the handoff slice, the\n'
    'board truthfully reports ``HANDOFF.md missing``. Runtime dependencies are\n'
    'PyYAML and jsonschema in addition to the standard library.\n'
    '"""',
    validator,
    count=1,
    flags=re.DOTALL,
)
validator = replace_once(
    validator,
    "from _shared import FrontmatterError, load_yaml, scan_sensitive, split_frontmatter",
    "from _support_shared import FrontmatterError, load_yaml, scan_sensitive, split_frontmatter",
    "target shared-helper import",
)
validator = replace_once(
    validator,
    '    for path in sorted(directory.glob(pattern)):\n        text = path.read_text(encoding="utf-8")',
    '    for path in sorted(directory.glob(pattern)):\n'
    '        # Queue README.md files are tracked placeholders, not records.\n'
    '        if path.name == "README.md":\n'
    '            continue\n'
    '        text = path.read_text(encoding="utf-8")',
    "queue placeholder exclusion",
)
validator = replace_once(
    validator,
    '    archived_count = len(list((coord / "archive").glob("*.md"))) \\\n'
    '        if (coord / "archive").is_dir() else 0',
    '    archived_count = sum(1 for p in (coord / "archive").glob("*.md")\n'
    '                         if p.name != "README.md") \\\n'
    '        if (coord / "archive").is_dir() else 0',
    "archive placeholder count exclusion",
)
validator = validator.replace(
    "Generated by coordination_validator.render_board.",
    "Generated by agent_coord.render_board.",
)
validator = replace_once(
    validator,
    "def write_board(root: Path) -> Path:",
    "def write_board(root: Path, *, timestamp: str | None = None) -> Path:",
    "deterministic board writer signature",
)
validator = replace_once(
    validator,
    '    stamp = datetime.now(timezone.utc).strftime(TS_FMT)',
    '    stamp = timestamp or datetime.now(timezone.utc).strftime(TS_FMT)\n'
    '    if _parse_ts(stamp) is None:\n'
    '        raise ValueError("timestamp must use YYYY-MM-DDTHH:MM:SSZ")',
    "deterministic board timestamp",
)
validator = replace_once(
    validator,
    '    board_path.write_text(render_board(root) + f"\\nGenerated: {stamp}\\n", encoding="utf-8")',
    '    board_path.write_text(render_board(root) + f"\\nGenerated: {stamp}\\n", '
    'encoding="utf-8", newline="\\n")',
    "platform-stable board newlines",
)
validator = replace_once(
    validator,
    '    parser.add_argument("--write-board", action="store_true",\n'
    '                         help="regenerate coordination/BOARD.md before validating")',
    '    parser.add_argument("--write-board", action="store_true",\n'
    '                         help="regenerate coordination/BOARD.md before validating")\n'
    '    parser.add_argument("--timestamp",\n'
    '                         help="fixed UTC timestamp for deterministic BOARD generation")',
    "target CLI timestamp argument",
)
validator = replace_once(
    validator,
    "        write_board(args.root)",
    "        write_board(args.root, timestamp=args.timestamp)",
    "target CLI deterministic board call",
)

shared = (STAGED / "_shared.py").read_text(encoding="utf-8")
shared = re.sub(
    r'\A""".*?"""',
    '"""Shared target-local helpers for portable CC_Loto support tools.\n\n'
    'Slice 2 installs ``agent_coord.py`` under the existing ``tools/support``\n'
    'convention; the handoff slice adds its second consumer there.\n'
    '"""',
    shared,
    count=1,
    flags=re.DOTALL,
)

placeholder_readmes = {
    "coordination/messages/README.md": (
        "# Active coordination messages\n\n"
        "Tracked placeholder for immutable unresolved `CX_` and `CC_` messages. "
        "`tools/support/agent_coord.py` ignores this README as a record.\n"
    ),
    "coordination/archive/README.md": (
        "# Coordination archive\n\n"
        "Tracked placeholder for confirmed, resolved messages and their immutable "
        "same-prefix resolution manifests. `tools/support/agent_coord.py` ignores "
        "this README as a record and archive-count entry.\n"
    ),
    "coordination/claims/README.md": (
        "# Coordination claims\n\n"
        "Tracked placeholder for task claims. Claims are repository-relative YAML "
        "records validated by `tools/support/agent_coord.py`.\n"
    ),
}

outputs = {
    "coordination/TEAM_PROTOCOL.md": team_protocol,
    "coordination/schemas/message.schema.json": (TEMPLATES / "message.schema.json").read_text(encoding="utf-8"),
    "coordination/schemas/claim.schema.json": (TEMPLATES / "claim.schema.json").read_text(encoding="utf-8"),
    "coordination/schemas/resolution-manifest.schema.json": (TEMPLATES / "resolution-manifest.schema.json").read_text(encoding="utf-8"),
    "coordination/templates/message.template.md": (TEMPLATES / "message.template.md").read_text(encoding="utf-8"),
    "coordination/templates/claim.template.yml": (TEMPLATES / "claim.template.yml").read_text(encoding="utf-8"),
    "coordination/templates/resolution-manifest.template.md": (TEMPLATES / "resolution-manifest.template.md").read_text(encoding="utf-8"),
    "coordination/templates/guidance-semantics.template.md": (TEMPLATES / "guidance-semantics.template.md").read_text(encoding="utf-8"),
    "tools/support/agent_coord.py": validator,
    "tools/support/_support_shared.py": shared,
    **placeholder_readmes,
}

allowed_guidance_placeholders = {
    "PROJECT_NAME", "CODEX_READ_ORDER", "CLAUDE_READ_ORDER",
    "CODEX_OWNERSHIP_TEXT", "CLAUDE_OWNERSHIP_TEXT",
    "CODEX_VALIDATION_TEXT", "CLAUDE_VALIDATION_TEXT",
    "CODEX_RECOVERY_TEXT", "CLAUDE_RECOVERY_TEXT",
    "CODEX_GATE_TEXT", "CLAUDE_GATE_TEXT", "READ_ORDER_DIFFERENCE",
    "OWNERSHIP_DIFFERENCE", "VALIDATION_DIFFERENCE", "RECOVERY_DIFFERENCE",
    "GATE_DIFFERENCE", "READ_ORDER_CHECK", "OWNERSHIP_CHECK",
    "VALIDATION_CHECK", "RECOVERY_CHECK", "GATE_CHECK",
}
placeholder_re = re.compile(r"\{\{([A-Z_]+)\}\}")
errors: list[str] = []
for rel, content in outputs.items():
    found = set(placeholder_re.findall(content))
    if rel == "coordination/templates/guidance-semantics.template.md":
        if found != allowed_guidance_placeholders:
            errors.append(f"{rel}: intentional placeholder set mismatch: {sorted(found)}")
    elif found:
        errors.append(f"{rel}: unresolved placeholders {sorted(found)}")
    scan_text = content
    if rel == "tools/support/_support_shared.py":
        scan_text, removed = re.subn(
            r"SENSITIVE_PATTERNS:.*?\n\]\n", "", content, count=1, flags=re.DOTALL
        )
        if removed != 1:
            errors.append(f"{rel}: sensitive-pattern declaration not found exactly once")
    hits = scan_sensitive(scan_text)
    if hits:
        errors.append(f"{rel}: sensitive patterns {hits}")
    for token in ("LLM_Wiki", "03_PKE", "Enconet", "xPY", "CC_FIN", "scripts/agent_coord.py"):
        if token in content:
            errors.append(f"{rel}: forbidden cross-target/workspace reference {token!r}")
if errors:
    raise AssertionError("\n".join(errors))

expected_paths = set(outputs) | {"coordination/BOARD.md"}
disposable_base = WIKI / ".tmp" / "loto-slice2-preflight"
disposable_base.mkdir(parents=True, exist_ok=True)
target = disposable_base / f"run-{uuid.uuid4().hex}"
target.mkdir()
try:
    for rel, content in outputs.items():
        path = target / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    completed = subprocess.run(
        [sys.executable, str(target / "tools/support/agent_coord.py"), str(target),
         "--write-board", "--timestamp", NOW],
        text=True,
        capture_output=True,
        check=False,
    )
    if completed.returncode != 0:
        raise AssertionError("target validator failed\n" + completed.stdout + completed.stderr)
    actual_paths = {
        path.relative_to(target).as_posix()
        for path in target.rglob("*")
        if path.is_file() and "__pycache__" not in path.parts
    }
    if actual_paths != expected_paths:
        raise AssertionError(f"inventory mismatch: {sorted(actual_paths)}")
    board = (target / "coordination/BOARD.md").read_text(encoding="utf-8")
    for required in (
        "- none", "- HANDOFF.md missing",
        "- Archive: 0 records in `coordination/archive/`", f"Generated: {NOW}",
    ):
        if required not in board:
            raise AssertionError(f"BOARD.md missing required initial state: {required}")
    link_re = re.compile(r"\]\(([^)#\s]+)")
    for path in target.rglob("*.md"):
        for link in link_re.findall(path.read_text(encoding="utf-8")):
            if link.startswith(("http://", "https://")):
                continue
            resolved = (path.parent / link).resolve()
            try:
                relative = resolved.relative_to(target)
            except ValueError:
                errors.append(f"{path.relative_to(target)}: escaping link {link!r}")
                continue
            if not resolved.exists() and not (LOTO / relative).exists():
                errors.append(f"{path.relative_to(target)}: dangling link {link!r}")
    if errors:
        raise AssertionError("\n".join(errors))

    out_resolved = OUT.resolve()
    out_resolved.relative_to(WIKI.resolve())
    if OUT.exists():
        shutil.rmtree(OUT)
    shutil.copytree(target, OUT, ignore=shutil.ignore_patterns("__pycache__"))
finally:
    shutil.rmtree(target, ignore_errors=True)

for rel in sorted(expected_paths):
    print("rendered", rel)
print("TARGET VALIDATION PASSED: 0 errors, 0 warnings")
print("INVENTORY PASSED: 14 exact files; HANDOFF.md missing; archive count 0")
print(f"RENDER_TIMESTAMP={NOW}")
