"""Inter-agent coordination tool (Task C2.4; ADR-0017, ADR-0018).

Commands: status | claim | release | message | acknowledge | validate

Paths resolve from this script's location (workspace scripts/), never the CWD.
Stdlib only. Non-zero exit on validation failure or refused operations.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COORD = ROOT / "Enconet" / "coordination"
MESSAGES_DIR = COORD / "messages"
ARCHIVE_DIR = COORD / "archive"
CLAIMS_DIR = COORD / "claims"
BOARD_PATH = COORD / "BOARD.md"
HANDOFF_POINTER = ROOT / "Enconet" / "HANDOFF.md"

AGENTS = {"codex": "CX_", "claude-code": "CC_"}
PREFIXES = {v: k for k, v in AGENTS.items()}
MESSAGE_TYPES = {
    "note", "review_request", "blocker", "question", "acknowledgement",
    "claim", "status",
}
TO_VALUES = {"codex", "claude-code", "both"}
DISPOSITION_TOKENS = ("resolved", "owner-accepted", "deferred-until")
CLAIM_DEFAULT_HOURS = 24
TS_FMT = "%Y-%m-%dT%H:%M:%SZ"
ID_TS_FMT = "%Y-%m-%dT%H%M%SZ"


def utc_now() -> datetime:
    return datetime.now(timezone.utc).replace(microsecond=0)


def fmt_ts(dt: datetime) -> str:
    return dt.strftime(TS_FMT)


def parse_ts(value: str) -> datetime | None:
    try:
        return datetime.strptime(value.strip(), TS_FMT).replace(tzinfo=timezone.utc)
    except ValueError:
        return None


# ---------------------------------------------------------------- parsing

def parse_kv_block(lines: list[str]) -> dict:
    """Parse a flat key/value block with simple '- item' lists (YAML subset)."""
    data: dict = {}
    current_list: str | None = None
    for raw in lines:
        if not raw.strip() or raw.strip().startswith("#"):
            continue
        stripped = raw.strip()
        if stripped.startswith("- ") and current_list:
            data[current_list].append(stripped[2:].strip())
            continue
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$", stripped)
        if not m:
            raise ValueError(f"unparseable line: {raw!r}")
        key, value = m.group(1), m.group(2).strip()
        if value == "" or value == "[]":
            data[key] = [] if key in ("related_files", "anticipated_files") else ""
            current_list = key if data[key] == [] else None
            if value == "":
                # may be a list header OR an empty scalar; allow both
                data.setdefault(key, "")
                current_list = key
                if not isinstance(data[key], list):
                    data[key] = []
        else:
            data[key] = "" if value in ("null", "~", "None") else value
            current_list = None
    return data


def parse_message(path: Path) -> tuple[dict | None, str | None]:
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n", text, re.DOTALL)
    if not m:
        return None, "missing frontmatter block"
    try:
        data = parse_kv_block(m.group(1).splitlines())
    except ValueError as exc:
        return None, str(exc)
    data["_body"] = text[m.end():]
    data["_path"] = path
    return data, None


def parse_claim(path: Path) -> tuple[dict | None, str | None]:
    try:
        data = parse_kv_block(path.read_text(encoding="utf-8").splitlines())
    except ValueError as exc:
        return None, str(exc)
    data["_path"] = path
    return data, None


def load_messages(directory: Path) -> tuple[list[dict], list[str]]:
    items, errors = [], []
    if not directory.is_dir():
        return items, errors
    for path in sorted(directory.glob("*.md")):
        data, err = parse_message(path)
        if err:
            errors.append(f"{path.name}: {err}")
        else:
            items.append(data)
    return items, errors


def load_claims() -> tuple[list[dict], list[str]]:
    items, errors = [], []
    if not CLAIMS_DIR.is_dir():
        return items, errors
    for path in sorted(CLAIMS_DIR.glob("*.yml")):
        data, err = parse_claim(path)
        if err:
            errors.append(f"claims/{path.name}: {err}")
        else:
            items.append(data)
    return items, errors


def claim_is_active(claim: dict, now: datetime) -> bool:
    if claim.get("status") != "active":
        return False
    expires = parse_ts(claim.get("expires_at_utc", ""))
    return expires is None or expires > now


# ---------------------------------------------------------------- board

def build_board_body() -> str:
    now = utc_now()
    active_msgs, _ = load_messages(MESSAGES_DIR)
    claims, _ = load_claims()
    archived_count = len(list(ARCHIVE_DIR.glob("*.md"))) if ARCHIVE_DIR.is_dir() else 0

    lines = [
        "# BOARD (generated)",
        "",
        "Generated by `scripts/agent_coord.py status --write` (ADR-0017). Never",
        "hand-edit; never treat as authoritative history — messages, claims, handoffs,",
        "and ADRs are the records.",
        "",
        "## Active claims",
        "",
    ]
    active_claims = [c for c in claims if claim_is_active(c, now)]
    if active_claims:
        for c in sorted(active_claims, key=lambda c: c.get("task", "")):
            lines.append(
                f"- `{c.get('task', '?')}` — {c.get('agent', '?')}, expires "
                f"{c.get('expires_at_utc', '?')}"
            )
    else:
        lines.append("- none")
    released = [c for c in claims if c.get("status") == "released"]
    expired = [
        c for c in claims
        if c.get("status") == "active" and not claim_is_active(c, now)
    ]
    if expired:
        lines += ["", "## Expired (not released — expiry does not imply completion)", ""]
        lines += [f"- `{c.get('task', '?')}` — {c.get('agent', '?')}" for c in expired]
    if released:
        lines += ["", "## Released claims", ""]
        lines += [
            f"- `{c.get('task', '?')}` — {c.get('agent', '?')}, released "
            f"{c.get('released_at_utc', '?')}"
            for c in sorted(released, key=lambda c: c.get("task", ""))
        ]

    lines += ["", "## Active messages", ""]
    if active_msgs:
        for msg in active_msgs:
            lines.append(
                f"- `{msg.get('message_id', msg['_path'].stem)}` — "
                f"{msg.get('type', '?')}, {msg.get('from_agent', '?')} → "
                f"{msg.get('to_agent', '?')}: {msg.get('task', '')}"
            )
    else:
        lines.append("- none")

    lines += ["", "## Pointers", ""]
    pointer = "HANDOFF.md missing"
    if HANDOFF_POINTER.is_file():
        for line in HANDOFF_POINTER.read_text(encoding="utf-8").splitlines():
            if "Authoritative record" in line:
                pointer = line.strip().lstrip("*").strip()
                break
    lines.append(f"- {pointer}")
    lines.append(f"- Archive: {archived_count} records in `coordination/archive/`")
    lines.append("")
    return "\n".join(lines)


def board_with_stamp(body: str) -> str:
    return body + f"\nGenerated: {fmt_ts(utc_now())}\n"


def strip_stamp(text: str) -> str:
    return re.sub(r"\nGenerated: .*\n?$", "\n", text)


# ---------------------------------------------------------------- commands

def cmd_status(args) -> int:
    body = build_board_body()
    if args.write:
        BOARD_PATH.write_text(board_with_stamp(body), encoding="utf-8")
        print(f"Wrote {BOARD_PATH.relative_to(ROOT)}")
    else:
        print(body)
    return 0


def cmd_claim(args) -> int:
    now = utc_now()
    claims, errors = load_claims()
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1
    files = args.files or []
    for c in claims:
        if not claim_is_active(c, now):
            continue
        if c.get("task") == args.task and c.get("agent") != args.agent:
            print(f"REFUSED: {args.task} actively claimed by {c.get('agent')}",
                  file=sys.stderr)
            return 1
        if c.get("agent") != args.agent:
            overlap = set(c.get("anticipated_files", [])) & set(files)
            if overlap:
                print(f"REFUSED: file overlap with {c.get('task')} "
                      f"({c.get('agent')}): {sorted(overlap)}", file=sys.stderr)
                return 1
    CLAIMS_DIR.mkdir(parents=True, exist_ok=True)
    path = CLAIMS_DIR / f"{args.task}.yml"
    existing = next((c for c in claims if c.get("task") == args.task
                     and c.get("agent") == args.agent
                     and c.get("status") == "active"), None)
    claimed_at = existing.get("claimed_at_utc") if existing else fmt_ts(now)
    expires = fmt_ts(now + timedelta(hours=args.hours))
    lines = [
        f"task: {args.task}",
        f"agent: {args.agent}",
        "status: active",
        f"claimed_at_utc: {claimed_at}",
        f"last_renewed_at_utc: {fmt_ts(now)}",
        f"expires_at_utc: {expires}",
        "anticipated_files:",
        *[f"  - {f}" for f in files],
    ]
    if args.note:
        lines.append(f"note: {args.note}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{'Renewed' if existing else 'Claimed'} {args.task} for {args.agent}, "
          f"expires {expires}")
    return 0


def cmd_release(args) -> int:
    path = CLAIMS_DIR / f"{args.task}.yml"
    if not path.is_file():
        print(f"REFUSED: no claim file for {args.task}", file=sys.stderr)
        return 1
    claim, err = parse_claim(path)
    if err:
        print(err, file=sys.stderr)
        return 1
    if claim.get("agent") != args.agent:
        print(f"REFUSED: {args.task} is owned by {claim.get('agent')}", file=sys.stderr)
        return 1
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"^status: .*$", "status: released", text, flags=re.MULTILINE)
    if "released_at_utc:" not in text:
        text = text.rstrip("\n") + f"\nreleased_at_utc: {fmt_ts(utc_now())}\n"
    path.write_text(text, encoding="utf-8")
    print(f"Released {args.task}")
    return 0


def write_message(from_agent: str, to_agent: str, msg_type: str, task: str,
                  topic: str, body: str, reply_to: str | None,
                  related_files: list[str]) -> Path:
    now = utc_now()
    prefix = AGENTS[from_agent]
    message_id = f"{prefix}{now.strftime(ID_TS_FMT)}_{topic}"
    path = MESSAGES_DIR / f"{message_id}.md"
    if path.exists():
        raise SystemExit(f"REFUSED: {path.name} already exists")
    lines = [
        "---",
        f"message_id: {message_id}",
        f"created_at_utc: {fmt_ts(now)}",
        f"from_agent: {from_agent}",
        f"to_agent: {to_agent}",
        f"type: {msg_type}",
        f"task: {task}",
        "related_files:" if related_files else "related_files: []",
        *[f"  - {f}" for f in related_files],
    ]
    if reply_to:
        lines.append(f"reply_to: {reply_to}")
    lines += ["---", "", body.strip(), ""]
    MESSAGES_DIR.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def cmd_message(args) -> int:
    body = Path(args.body_file).read_text(encoding="utf-8") if args.body_file \
        else (args.body or "")
    if not body.strip():
        print("REFUSED: empty body (use --body or --body-file)", file=sys.stderr)
        return 1
    path = write_message(args.from_agent, args.to, args.type, args.task,
                         args.topic, body, args.reply_to, args.files or [])
    print(f"Wrote {path.relative_to(ROOT)}")
    return 0


def cmd_acknowledge(args) -> int:
    everything = load_messages(MESSAGES_DIR)[0] + load_messages(ARCHIVE_DIR)[0]
    target = next((m for m in everything
                   if m.get("message_id") == args.message_id), None)
    if target is None:
        print(f"REFUSED: unknown message_id {args.message_id}", file=sys.stderr)
        return 1
    body = args.body or f"Acknowledged: {args.message_id}."
    topic = f"ack-{args.message_id.split('_', 2)[-1][:60]}"
    path = write_message(args.agent, target.get("from_agent", "both"),
                         "acknowledgement", target.get("task", ""),
                         topic, body, args.message_id, [])
    print(f"Wrote {path.relative_to(ROOT)}")
    return 0


# ---------------------------------------------------------------- validate

def is_manifest(path: Path) -> bool:
    return "manifest" in path.stem.lower()


def cmd_validate(args) -> int:
    errors: list[str] = []
    warnings: list[str] = []
    now = utc_now()

    active, parse_errs = load_messages(MESSAGES_DIR)
    archived, parse_errs2 = load_messages(ARCHIVE_DIR)
    errors += parse_errs + parse_errs2
    everything = active + archived

    seen_ids: dict[str, str] = {}
    for msg in everything:
        if is_manifest(msg["_path"]):
            continue  # resolution manifests are a separate record type (ADR-0018)
        name = msg["_path"].name
        mid = msg.get("message_id", "")
        if not mid:
            errors.append(f"{name}: missing message_id")
            continue
        if mid != msg["_path"].stem:
            errors.append(f"{name}: message_id does not match filename")
        if mid in seen_ids:
            errors.append(f"{name}: duplicate message_id (also {seen_ids[mid]})")
        seen_ids[mid] = name
        prefix = name[:3]
        expected_agent = PREFIXES.get(prefix)
        if expected_agent is None:
            errors.append(f"{name}: unknown author prefix")
        elif msg.get("from_agent") != expected_agent:
            errors.append(f"{name}: from_agent {msg.get('from_agent')!r} "
                          f"contradicts prefix {prefix}")
        if msg.get("type") not in MESSAGE_TYPES:
            errors.append(f"{name}: invalid type {msg.get('type')!r}")
        if msg.get("to_agent") not in TO_VALUES:
            errors.append(f"{name}: invalid to_agent {msg.get('to_agent')!r}")
        if parse_ts(msg.get("created_at_utc", "")) is None:
            errors.append(f"{name}: invalid created_at_utc")
        reply_to = msg.get("reply_to", "")
        if reply_to and reply_to not in {m.get("message_id") for m in everything}:
            errors.append(f"{name}: reply_to {reply_to!r} not found in "
                          "messages/ or archive/")

    replied_ids = {m.get("reply_to") for m in everything if m.get("reply_to")}
    for msg in active:
        if msg.get("type") == "blocker" and msg.get("message_id") not in replied_ids:
            errors.append(f"{msg['_path'].name}: unacknowledged active blocker")
        if "both agents synchronized" in msg.get("_body", "").lower() \
                and msg.get("message_id") not in replied_ids:
            warnings.append(f"{msg['_path'].name}: claims synchronization without "
                            "a confirming reply from the other agent")

    manifest_texts: dict[str, str] = {}
    if ARCHIVE_DIR.is_dir():
        for path in ARCHIVE_DIR.glob("*.md"):
            if is_manifest(path):
                manifest_texts[path.name] = path.read_text(encoding="utf-8")
    for msg in archived:
        path = msg["_path"]
        if is_manifest(path):
            continue
        mid = msg.get("message_id", path.stem)
        prefix = path.name[:3]
        covering = [n for n, t in manifest_texts.items()
                    if mid in t and n.startswith(prefix)]
        if not covering:
            errors.append(f"archive/{path.name}: no same-prefix resolution manifest "
                          "references it")
        elif msg.get("type") == "blocker":
            if not any(tok in manifest_texts[n].lower()
                       for n in covering for tok in DISPOSITION_TOKENS):
                errors.append(f"archive/{path.name}: archived blocker without a "
                              "disposition (resolved/owner-accepted/deferred-until)")

    claims, claim_errs = load_claims()
    errors += claim_errs
    active_claims = [c for c in claims if claim_is_active(c, now)]
    for i, a in enumerate(active_claims):
        for b in active_claims[i + 1:]:
            if a.get("agent") == b.get("agent"):
                continue
            if a.get("task") == b.get("task"):
                errors.append(f"claims: {a.get('task')} actively claimed by both agents")
            overlap = set(a.get("anticipated_files", [])) & \
                set(b.get("anticipated_files", []))
            if overlap:
                errors.append(f"claims: {a.get('task')} and {b.get('task')} overlap "
                              f"on {sorted(overlap)}")
    for c in claims:
        for field in ("task", "agent", "status", "claimed_at_utc"):
            if not c.get(field):
                errors.append(f"claims/{c['_path'].name}: missing {field}")
        if c.get("agent") not in AGENTS:
            errors.append(f"claims/{c['_path'].name}: unknown agent {c.get('agent')!r}")

    if not BOARD_PATH.is_file():
        errors.append("BOARD.md missing (generate: agent_coord.py status --write)")
    elif strip_stamp(BOARD_PATH.read_text(encoding="utf-8")).rstrip() \
            != build_board_body().rstrip():
        errors.append("BOARD.md is stale (regenerate: agent_coord.py status --write)")

    for w in warnings:
        print(f"WARN : {w}")
    for e in errors:
        print(f"ERROR: {e}", file=sys.stderr)
    print(f"validate: {len(errors)} error(s), {len(warnings)} warning(s); "
          f"{len(active)} active message(s), {len(archived)} archived, "
          f"{len(active_claims)} active claim(s).")
    return 1 if errors else 0


# ---------------------------------------------------------------- main

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("status", help="print (or --write) BOARD.md")
    p.add_argument("--write", action="store_true")
    p.set_defaults(func=cmd_status)

    p = sub.add_parser("claim", help="claim or renew a task")
    p.add_argument("task")
    p.add_argument("--agent", required=True, choices=sorted(AGENTS))
    p.add_argument("--files", nargs="*")
    p.add_argument("--note")
    p.add_argument("--hours", type=int, default=CLAIM_DEFAULT_HOURS)
    p.set_defaults(func=cmd_claim)

    p = sub.add_parser("release", help="release an owned claim")
    p.add_argument("task")
    p.add_argument("--agent", required=True, choices=sorted(AGENTS))
    p.set_defaults(func=cmd_release)

    p = sub.add_parser("message", help="write an immutable message")
    p.add_argument("--from", dest="from_agent", required=True, choices=sorted(AGENTS))
    p.add_argument("--to", required=True, choices=sorted(TO_VALUES))
    p.add_argument("--type", required=True, choices=sorted(MESSAGE_TYPES))
    p.add_argument("--task", required=True)
    p.add_argument("--topic", required=True,
                   help="kebab-case topic used in the filename")
    p.add_argument("--body")
    p.add_argument("--body-file")
    p.add_argument("--reply-to")
    p.add_argument("--files", nargs="*")
    p.set_defaults(func=cmd_message)

    p = sub.add_parser("acknowledge", help="acknowledge an existing message")
    p.add_argument("message_id")
    p.add_argument("--agent", required=True, choices=sorted(AGENTS))
    p.add_argument("--body")
    p.set_defaults(func=cmd_acknowledge)

    p = sub.add_parser("validate", help="validate protocol state (exit 1 on errors)")
    p.set_defaults(func=cmd_validate)

    args = parser.parse_args()
    sys.exit(args.func(args))


if __name__ == "__main__":
    main()
